privilegies:
  service:
    port: 8050
    image:
      name: sivashov/privilegies-service
      version: "1.1"
    database:
      name: postgres

flights:
  service:
    port: 8060
    image:
      name: sivashov/flights-service
      version: "1.1"
    database: 
      name: postgres

tickets:
  service:
    port: 8070
    image:
      name: sivashov/tickets-service
      version: "1.1"
    database: 
      name: postgres

gateway:
  service:
    port: 8080
    image:
      name: sivashov/gateway-service
      version: "1.1"
    isGateway: true